on: [push]

name: test

jobs:
  build:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: install tools
        run: |
          npm install

      - name: start dependencies
        uses: hoverkraft-tech/compose-action@v2.2.0
        with:
          compose-file: "./tests/compose.yaml"
          down-flags: "--volumes"
          up-flags: "--wait"
          services: |
            engine
            postgres
            app_mypostgres
            plugin

      - name: run tests
        run: |
          npm run test
